pull_requests:
  do_not_increment_build_number: true
build:
  verbosity: minimal

install:
  - ps: Install-Product node 6.5.0 x64
  - npm install -g npm@5.10.0
  - npm install -g mocha

build_script:
  - npm i
  - npm run vscode:prepublish

test_script:
  - node --version
  - npm run test
