trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    npm run vscode:prepublish
  displayName: 'pack extension'

- script: |
    npm run test --silent
  displayName: npm test
  env:
    DISPLAY: ':99.0'

- script: |
    npm run testintegration --silent
  displayName: npm testintegration
  env:
    DISPLAY: ':99.0'
  condition: ne(variables['Agent.OS'], 'Linux') # Sad :(
