trigger:
  tags:
    include:
      - v*

pr: none

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    npm run test --silent
  displayName: npm test
  env:
    DISPLAY: ':99.0'

- script: |
    npm run clean
    npm run publish-market -- -p $vsceToken
  displayName: 'publish to marketplace'
  env:
    vsceToken: $(VSCE_TOKEN)